//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using Utilitarios.Enumerators;
    using Utilitarios.Extencions;

    public partial class Pedido
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Pedido()
        {
            this.ItensPedido = CtrlSession.context.ItensPedido.Where(x => x.PedidoId == this.Id).ToList();
        }
    
        public long Id { get; set; }
        public Nullable<long> ClienteId { get; set; }
        public Nullable<System.DateTime> Data { get; set; }
        public Nullable<decimal> Valor { get; set; }
        public Nullable<byte> Situacao { get; set; }
        public Nullable<byte> NumeroParcela { get; set; }
        public Nullable<decimal> ValorTotalComicao { get; set; }
    
        public virtual Cliente Cliente { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual List<ItensPedido> ItensPedido { get; set; }

        public virtual String NomeCliente { get { return this.Cliente.IsNull() ? "" : this.Cliente.Nome; } }
        public virtual String ValorFormatado { get { return this.Valor.Value.ToString("C"); } }
        public virtual String ValorTotalComissaoFormatado { get { return this.ValorTotalComicao.Value.ToString("C"); } }
        public virtual String StringSituacao { get { return ((ESituacaoPedido)this.Situacao.Value).Descricao(); } }
        public virtual String ObservacaosConcatenadas { get { return Observacao.GetObservacoes(ETipoObservacao.Pedido, this.Id); } }
        
    }
}
